version: '3'

services:
  jambb-api:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - postgresdb
    volumes:
      - ./:/home/slay/
    environment:
      DJANGO_SETTINGS_MODULE: slay.settings.local

  postgresdb: # name of the third service
    image: postgres:10-alpine # specify image to build container from
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=slay
    env_file:
      - .env
    ports:
      - '5442:5442' # specify port forwarding
